name: Make + clang tidy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
defaults:
  run:
    shell: bash
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repo
      uses: actions/checkout@v3
    - name: Install tools
      run: |
        sudo apt-get -y install llvm
        sudo apt-get -y install lld
    - name: make
      run: CC=clang LD=lld make
    - name: check syntax
      run: make clang-tidy >> $GITHUB_OUTPUT
    - name: check ct output
      run: |
        if [ -s diff.txt ]; then
          exit 1
        fi
