name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: brew install nasm

      - name: make OS.iso
        run: make

      - name: Store iso
        uses: actions/upload-artifact@v3
        with:
          name: pacman.iso
          path: pacman.iso
